# Imports

In [325]:
import numpy as np
import time
from numpy.linalg import inv

In [326]:
def obj (x) :
    return np.power(x, 4) + np.power(x, 3) - 10*np.square(x) + x + 5

# Naive

In [368]:
x_min = -2.6629
noParticles = 5
w = 0.1
c1 = 2
c2 = 2
r1 = np.random.rand (noParticles, 1)
r2 = np.random.rand (noParticles, 1)

eps = 0.00001
xs = eps*np.random.rand(noParticles, 1) + x_min
vs = eps*np.random.rand(noParticles, 1)

print (xs)
print (vs)

[[-2.6628907 ]
 [-2.66289252]
 [-2.66289547]
 [-2.66289948]
 [-2.66289704]]
[[1.05852703e-06]
 [4.77887310e-08]
 [9.99247787e-06]
 [8.69587330e-06]
 [5.10201079e-06]]


In [369]:
noIter = 10

xsave = xs
vsave = vs

for i in range(0, noIter) :
    mats = [np.array ([
    [1, 1, 0], [-(c1*rr1 + c2*rr2), w, (c1*rr1 + c2*rr2)*x_min], [0, 0, 1]
    ]) for rr1,rr2 in zip(r1[:,0], r2[:,0])]

    vecs = np.array ([np.dot (m, np.array([x, v, 1])) for m, x, v in zip (mats, xs[:,0], vs[:,0])])

    xs = vecs[:,0].reshape (-1, 1)
    vs = vecs[:,1].reshape (-1, 1)

In [370]:
xper = (xs - xsave)/xsave * 100
vper = (vs - vsave)/vsave * 100

print (np.abs(xs - x_min))
print (np.abs(vs))

[[2.88051574e-05]
 [4.67401935e-04]
 [1.31178773e-05]
 [7.12212624e-07]
 [5.18696553e-05]]
[[1.20729589e-04]
 [4.54966681e-04]
 [3.58482477e-06]
 [3.84990401e-06]
 [2.87881051e-04]]
